print("Welcome to questionnaire bot!")
name = input("Your name: ")
surname = input("Your surname: ")
father = input("Your patronymic: ")
age = input("Your age: ")
number = input("Your phone number with region: +")
place = input("Where you live: ")
game = input("Your favourite (you can type not favourite) game: ")
nickname = input(f"Name (nickname) в {game}: ")
print(f"Surname, name and patronymic: {surname} {name} {father}")
print(f"Age: {age}")
print(f"Phone number: +{number}")
print(f"Place, where {name} lives: {place}")
print(f"Favourite (maybe not favourite) game: {game}")
print(f"Name (nickname) in {game}: {nickname}")
print("Now copy it and you can delete other!")